#!/usr/bin/env node

var StringDecoder = require('string_decoder').StringDecoder;
var fs = require('fs')
var foreverMonitor = require('forever-monitor');
var l = require('./lib/log.js')
l.context = __filename

var processes = JSON.parse(fs.readFileSync(__dirname + '/processes.json'))

var i = 0
var startNextProcess = function(process) {
  if (process == undefined) return done() 
  var child = new (foreverMonitor.Monitor)(process.file, process.options)
  child.on('start', function(foreverProcess, data) {
    l.g('Starting ' + process.file)
  })
  child.on('stdout', function(stdout) {
    var decoder = new StringDecoder('utf8');
    stdout = decoder.write(stdout)
    if (stdout.search(process.readyMessage) !== -1) {
      l.g(process.file + ' child is ready')
      return startNextProcess(processes.shift())
    }
  })
  child.start()
}

var done = function() {
  console.log(fs.readFileSync(__dirname + '/util/fido.txt', 'utf-8'))
  return l.g('All systems go.')
}

startNextProcess(processes.shift())


